### ISSUE TITLE
gmime hangs when decrypting an email (from notmuch) when a TOFU conflict is encountered.

### ISSUE THREAD

**Issue by muelli** [jstedfast/gmime#4]
```

/usr/bin/notmuch show --format=sexp --format-version=1 --decrypt --exclude=false ' thread:0000000000001885 and ( tag:unread )'

#0  0x00007fa50708a530 in __poll_nocancel ()
    at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fa507cfef5f in poll (__timeout=10000, __nfds=5, 
    __fds=0x7ffe9d71a4b0) at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  gpg_ctx_op_step (gpg=gpg@entry=0x55eb6dd218c0, 
    err=err@entry=0x7ffe9d71b5d8) at gmime-gpg-context.c:1631
#3  0x00007fa507d00733 in gpg_decrypt_session (context=<optimized out>, 
    session_key=0x0, istream=<optimized out>, ostream=<optimized out>, 
    err=0x7ffe9d71b5d8) at gmime-gpg-context.c:2147
#4  0x00007fa507d07b28 in g_mime_multipart_encrypted_decrypt_session (
    mpe=<optimized out>, ctx=ctx@entry=0x55eb6dd1c9c0, 
    session_key=session_key@entry=0x0, result=result@entry=0x7ffe9d71b5e0, 
    err=err@entry=0x7ffe9d71b5d8) at gmime-multipart-encrypted.c:407
#5  0x00007fa507d07d0d in g_mime_multipart_encrypted_decrypt (
    mpe=<optimized out>, ctx=ctx@entry=0x55eb6dd1c9c0, 
    result=result@entry=0x7ffe9d71b5e0, err=err@entry=0x7ffe9d71b5d8)
    at gmime-multipart-encrypted.c:295
#6  0x000055eb6d77579e in node_decrypt_and_verify (cryptoctx=0x55eb6dd1c9c0, 
    part=0x55eb6dd1ee40, node=0x55eb6dd1d4b0) at mime-node.c:182
#7  _mime_node_create (part=0x55eb6dd1ee40, parent=0x55eb6dd22d90)
    at mime-node.c:258
#8  mime_node_child (parent=parent@entry=0x55eb6dd22d90, child=child@entry=0)
    at mime-node.c:296
#9  0x000055eb6d77281d in format_part_sprinter (ctx=0x55eb6dcfe7b0, 
    sp=0x55eb6dcfd8b0, node=0x55eb6dd22d90, first=1, output_body=1, 
    include_html=0) at notmuch-show.c:563
#10 0x000055eb6d772f36 in format_part_sprinter_entry (ctx=<optimized out>, 
    sp=<optimized out>, node=<optimized out>, indent=<optimized out>, 
    params=<optimized out>) at notmuch-show.c:670
#11 0x000055eb6d771a70 in show_message (ctx=ctx@entry=0x55eb6dcd71d0, 
    sp=sp@entry=0x55eb6dcfd8b0, message=message@entry=0x55eb6dd184b0, 
    indent=indent@entry=1, params=params@entry=0x7ffe9d71b830, 
    format=<optimized out>) at notmuch-show.c:827
#12 0x000055eb6d771b69 in show_messages (ctx=ctx@entry=0x55eb6dcd71d0, 
    format=format@entry=0x55eb6d980d40 <format_sexp>, 
    sp=sp@entry=0x55eb6dcfd8b0, messages=0x55eb6dd1e910, 
    indent=indent@entry=1, params=params@entry=0x7ffe9d71b830)
    at notmuch-show.c:863
#13 0x000055eb6d771bac in show_messages (ctx=ctx@entry=0x55eb6dcd71d0, 
    format=format@entry=0x55eb6d980d40 <format_sexp>, 
    sp=sp@entry=0x55eb6dcfd8b0, messages=0x55eb6dcfe300, 
    indent=indent@entry=0, params=params@entry=0x7ffe9d71b830)
    at notmuch-show.c:871
#14 0x000055eb6d77384f in do_show (params=0x7ffe9d71b830, sp=0x55eb6dcfd8b0, 
    format=0x55eb6d980d40 <format_sexp>, query=0x55eb6dcdd1e0, 
    ctx=0x55eb6dcd71d0) at notmuch-show.c:959
#15 notmuch_show_command (config=0x55eb6dcd71d0, argc=<optimized out>, 
    argv=<optimized out>) at notmuch-show.c:1171
#16 0x000055eb6d76562f in main (argc=<optimized out>, argv=0x7ffe9d71bce8)
    at notmuch.c:421



gpg2 --verbose --no-secmem-warning --no-greeting --no-tty --charset=UTF-8 --status-fd=16 --command-fd=17 --use-agent --decrypt --output -

#0  0x00007f503b88d5a0 in __read_nocancel () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000557612c95661 in read (__nbytes=1, __buf=0x5576136ac930, __fd=17) at /usr/include/x86_64-linux-gnu/bits/unistd.h:44
#2  myread (count=1, buf=0x5576136ac930, fd=17) at ../../g10/cpr.c:377
#3  do_get_from_fd (keyword=keyword@entry=0x557612d1a049 "tofu.conflict", hidden=hidden@entry=0, getbool=getbool@entry=0)
    at ../../g10/cpr.c:434
#4  0x0000557612c95f17 in cpr_get (keyword=keyword@entry=0x557612d1a049 "tofu.conflict", prompt=<optimized out>) at ../../g10/cpr.c:483
#5  0x0000557612cd7dbe in ask_about_binding (now=1492082038, user_id=0x5576136978fc "xxx <foo@bar>", 
    email=0x55761367ba00 "a@dress", fingerprint=0x5576136986e0 "XXXFPRXXX", 
    conflict_set=<optimized out>, trust_level=<synthetic pointer>, policy=<synthetic pointer>, ctrl=0x557613664b60) at ../../g10/tofu.c:1962
#6  get_trust (ctrl=ctrl@entry=0x557613664b60, pk=pk@entry=0x557613699fd0, 
    fingerprint=fingerprint@entry=0x5576136986e0 "XXXFPRXXX", 
    email=email@entry=0x55761367ba00 "a@dress", 
    user_id=user_id@entry=0x5576136978fc "xxx <foo@bar>", may_ask=<optimized out>, may_ask@entry=1, 
    policyp=0x7ffc4a63859c, conflict_setp=0x7ffc4a6385a0, now=1492082038) at ../../g10/tofu.c:2761
#7  0x0000557612cd9443 in tofu_get_validity (ctrl=ctrl@entry=0x557613664b60, pk=pk@entry=0x557613699fd0, user_id_list=0x5576136ae310, 
    may_ask=may_ask@entry=1) at ../../g10/tofu.c:3730
#8  0x0000557612ccfce6 in tdb_get_validity_core (ctrl=ctrl@entry=0x557613664b60, kb=0x5576136945a0, kb@entry=0x0, 
    pk=pk@entry=0x557613699fd0, uid=uid@entry=0x0, main_pk=main_pk@entry=0x557613699fd0, sig=sig@entry=0x55761368c7f0, may_ask=1)
    at ../../g10/trustdb.c:1150
#9  0x0000557612ccbcfa in get_validity (ctrl=ctrl@entry=0x557613664b60, kb=kb@entry=0x0, pk=pk@entry=0x557613699fd0, uid=uid@entry=0x0, 
    sig=sig@entry=0x55761368c7f0, may_ask=may_ask@entry=1) at ../../g10/trust.c:354
#10 0x0000557612ca0771 in check_signatures_trust (ctrl=0x557613664b60, sig=sig@entry=0x55761368c7f0) at ../../g10/pkclist.c:572
#11 0x0000557612c846a5 in check_sig_and_print (c=c@entry=0x5576136a67b0, node=node@entry=0x5576136ad3e0) at ../../g10/mainproc.c:2144
#12 0x0000557612c851ab in proc_tree (node=<optimized out>, c=0x5576136a67b0) at ../../g10/mainproc.c:2332
#13 release_list (c=c@entry=0x5576136a67b0) at ../../g10/mainproc.c:127
#14 0x0000557612c8589c in do_proc_packets (ctrl=0x557613664b60, c=0x5576136a67b0, a=0x5576136701e0) at ../../g10/mainproc.c:1480
#15 0x0000557612c85b0a in proc_packets (ctrl=ctrl@entry=0x557613664b60, anchor=anchor@entry=0x557613678120, a=0x5576136701e0)
    at ../../g10/mainproc.c:1205
#16 0x0000557612c7445f in handle_compressed (ctrl=0x557613664b60, procctx=procctx@entry=0x557613678120, cd=0x5576136a0970, 
    callback=callback@entry=0x0, passthru=passthru@entry=0x0) at ../../g10/compress.c:324
#17 0x0000557612c82b20 in proc_compressed (c=c@entry=0x557613678120, pkt=pkt@entry=0x55761369f730) at ../../g10/mainproc.c:824
#18 0x0000557612c857cb in do_proc_packets (ctrl=0x557613664b60, c=0x557613678120, a=0x5576136701e0) at ../../g10/mainproc.c:1437
#19 0x0000557612c85b0a in proc_packets (ctrl=ctrl@entry=0x557613664b60, anchor=anchor@entry=0x5576136743a0, a=0x5576136701e0)
    at ../../g10/mainproc.c:1205
#20 0x0000557612ca5501 in decrypt_data (ctrl=0x557613664b60, procctx=procctx@entry=0x5576136743a0, ed=0x557613679f30, dek=0x7f503ce15008)
    at ../../g10/decrypt-data.c:253
#21 0x0000557612c82322 in proc_encrypted (c=c@entry=0x5576136743a0, pkt=pkt@entry=0x557613665a40) at ../../g10/mainproc.c:603
#22 0x0000557612c8581b in do_proc_packets (ctrl=0x557613664b60, c=0x5576136743a0, a=0x5576136701e0) at ../../g10/mainproc.c:1435
#23 0x0000557612c85d91 in proc_encryption_packets (ctrl=ctrl@entry=0x557613664b60, anchor=anchor@entry=0x0, a=a@entry=0x5576136701e0)
    at ../../g10/mainproc.c:1304
#24 0x0000557612ca40d6 in decrypt_message (ctrl=0x557613664b60, filename=<optimized out>) at ../../g10/decrypt.c:88
#25 0x0000557612c60f06 in main (argc=<optimized out>, argv=<optimized out>) at ../../g10/gpg.c:4197

```

With  `--batch` it shouldn't hang, because with the new TOFU policy, gpg seems to require user interaction (unless --batch is given).
Hence notmuch hangs when encountering new conflicting (uid,key)-bindings under the TOFU model.

I see

```
	if (!gpg->need_passwd) {
		/* only use batch mode if we don't intend on using the
                   interactive --command-fd option to send it the
                   user's password */
		g_ptr_array_add (args, "--batch");
	}
	
	g_ptr_array_add (args, "--charset=UTF-8");
	
	(*strv)[v++] = buf = g_strdup_printf ("--status-fd=%d", status_fd);
	g_ptr_array_add (args, buf);
	
	if (gpg->need_passwd && !gpg->override_session_key) {
		(*strv)[v++] = buf = g_strdup_printf ("--command-fd=%d", secret_fd);
		g_ptr_array_add (args, buf);
}
```

in https://github.com/jstedfast/gmime/blob/gmime-2-6/gmime/gmime-gpg-context.c

Maybe an option for gmime is to make gpg use an agent. Probably at the expense to break the offered API reg. password handling.  Another option is to not support newer gpg versions with TOFU model.  If that route is chosen, it would be nice to make a statement about it, so that distributions can model the incompatibility.

**Comment by jstedfast** [comment]
notmuch is using gmime 3.0 now, so I'm going to close this as resolved.

There's no fix for this in 2.x :-\
