### ISSUE TITLE
stack overread on malformed input in uudecode

### ISSUE THREAD

**Issue by hannob** [jstedfast/gmime#54]
To see this bug you have to compile with address sanitizer (-fsanitize=address in CFLAGS+LDFLAGS).

A malformed input will lead to an out of bounds stack read in the uudecode example code:
```
echo -e "begin a\n\x00" | examples/uudecode -
```

Error:
```
==11077==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffd7d4f042f at pc 0x0000004f84a4 bp 0x7ffd7d4f03d0 sp 0x7ffd7d4f03c8
READ of size 1 at 0x7ffd7d4f042f thread T0
    #0 0x4f84a3 in uudecode /mnt/ram/gmime/examples/uudecode.c:198:14
    #1 0x4f84a3 in main /mnt/ram/gmime/examples/uudecode.c:240
    #2 0x7f2e531584ea in __libc_start_main (/lib64/libc.so.6+0x244ea)
    #3 0x41c479 in _start (/mnt/ram/gmime/examples/uudecode+0x41c479)

Address 0x7ffd7d4f042f is located in stack of thread T0 at offset 79 in frame
    #0 0x4f6e2f in main /mnt/ram/gmime/examples/uudecode.c:228

  This frame has 8 object(s):
    [32, 36) 'argc.addr.i' (line 67)
    [48, 56) 'argv.addr.i' (line 67)
    [80, 4176) 'inbuf.i' (line 72) <== Memory access at offset 79 underflows this variable
    [4304, 4312) 'q.i' (line 72)
    [4336, 4344) 'err.i' (line 74)
    [4368, 8468) 'outbuf.i' (line 76)
    [8736, 8740) 'save.i' (line 78)
    [8752, 8756) 'state.i' (line 80)

**Comment by jstedfast** [comment]
Looks like a simple fix of:

```c
midline = n > 0 && inbuf[n - 1] != '\n';
```

would work on line 198 in examples/uudecode.c

Could you verify? I don't have a Linux machine handy at the moment and won't for quite some time.
